name: md-status-surv
is_for_killer: false
model_type: status
cs: surv_player
crop: status__surv
norm_means: [0.485, 0.456, 0.406]
norm_std: [0.229, 0.224, 0.225]
training:
  epochs: 30
  batch_size: 64
  adam_lr: 1.0e-3
