DEFAULT_SCREENSHOT_W = 1920
DEFAULT_SCREENSHOT_H = 1080
DEFAULT_SCREENSHOT_SIZE = (DEFAULT_SCREENSHOT_W, DEFAULT_SCREENSHOT_H)

DEFAULT_DBD_VERSION = "7.5.0"
DEFAULT_MAX_DBD_VERSION = None
DEFAULT_DBDVR = [DEFAULT_DBD_VERSION, DEFAULT_MAX_DBD_VERSION]
