name: surv
src_fd_rp: data/img/pending
dst_fd_rp: data/crops
version_range:
  - "8.1.0-ptb"  # the 2v8 adaptation
  - null
img_size: [1920, 1080]
crops:
  player__surv:
    - [72, 254, 992, 375]
    - [72, 375, 992, 496]
    - [72, 496, 992, 617]
    - [72, 617, 992, 738]
allow:
  overlap: false
  overboard: false
offset: null
