name: killer
src_fd_rp: data/img/pending
dst_fd_rp: data/crops
version_range:
  - "8.1.0-ptb"  # the 2v8 adaptation
  - null
img_size: [1920, 1080]
crops:
  player__killer:
    - [72, 730, 992, 851]
allow:
  overlap: false
  overboard: false
offset: 4
