name: surv_player
src_fd_rp: data/crops/player__surv
dst_fd_rp: data/crops
version_range:
  - "8.1.0-ptb"  # the 2v8 adaptation
  - null
img_size:
  cs: surv
  fmt: player__surv
crops:
  addons__surv:
    - [479, 58, 520, 99]
    - [525, 58, 566, 99]
  character__surv:
    - [120, 5, 600, 38]
  item__surv:
    - [411, 57, 454, 100]
  offering__surv:
    - [350, 55, 394, 103]
  perks__surv:
    - [110, 52, 166, 107]
    - [166, 52, 222, 107]
    - [222, 52, 278, 107]
    - [278, 52, 334, 107]
  points__surv:
    - [580, 54, 750, 104]
  prestige__surv:
    - [0, 19, 96, 111]
  status__surv:
    - [117, 5, 146, 40]
allow:
  overlap: false
  overboard: false
offset: null
