name: killer_player
src_fd_rp: data/crops/player__killer
dst_fd_rp: data/crops
dbdvr:
  - "8.1.0-ptb"  # the 2v8 adaptation
  - null
img_size:
  cs: killer
  fmt: player__killer
crops:
  addons__killer:
    - [479, 65, 520, 106]
    - [525, 65, 566, 106]
  character__killer:
    - [120, 9, 600, 42]
  item__killer:
    - [411, 64, 454, 106]
  offering__killer:
    - [350, 60, 395, 108]
  perks__killer:
    - [111, 57, 166, 112]
    - [166, 57, 221, 112]
    - [221, 57, 276, 112]
    - [276, 57, 331, 112]
  points__killer:
    - [582, 61, 752, 111]
  prestige__killer:
    - [0, 22, 98, 115]
  status__killer:
    - [117, 10, 148, 47]
allow:
  overlap: false
  overboard: true
offset: null
