name: surv_player
src_fd_rp: data/crops/player__surv
dst_fd_rp: data/crops
version_range:
  - "7.4.0-ptb"  # the Banner and Badge patch
  - "8.1.0-ptb"  # the 2v8 adaptation
img_size:
  cs: surv
  fmt: player__surv
crops:
  addons__surv:
    - [483, 58, 524, 99]
    - [524, 58, 565, 99]
  character__surv:
    - [124, 5, 600, 38]
  item__surv:
    - [422, 59, 465, 101]
  offering__surv:
    - [356, 54, 405, 107]
  perks__surv:
    - [123, 50, 178, 106]
    - [178, 50, 233, 106]
    - [233, 50, 288, 106]
    - [288, 50, 343, 106]
  points__surv:
    - [580, 54, 750, 104]
  prestige__surv:
    - [0, 0, 117, 116]
  status__surv:
    - [124, 5, 155, 46]
allow:
  overlap: false
  overboard: false
offset: null
